include: package:lints/recommended.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - avoid_print
    - prefer_final_fields
    - prefer_final_locals
    - sort_constructors_first
    - always_declare_return_types
